### PR TITLE
Favorites store, documentation, and more

### PR DESCRIPTION
**Pull request by MarkJerde**
Hi Gennadiy,
Here are commits that provide the Favories Store requested in issue #75 for which I provided a demo a month ago.

Also included are commits for some features I use regularly:
* An indicator via the menu icon when a large network copy is transferring and will be lost if the user switches apps.  (Value-add directly related to clipboard.)
* Password detection and avoidance.
* Auto-save clippings when they fall off the end of the clipping store.  Avoids losing something important.  Defaults to off so it doesn't create a mess for those who don't seek it out.

I also added a help text that can be viewed on GitHub and linked it from the readme.md.

Thank you!
Mark

### CODE REVIEW

**Comment by TermiT** [comment]
Everything looks cool, except I don't like the idea of recognition passwords (63b90b0). If you don't mind I will merge everything except it. Thanks.

**Comment by MarkJerde** [comment]
Hi Gennadiy,
Can you describe your concern with the password recognition?

The implementation that has been provided:
* Extends upon an existing feature of Flycut that doesn't work that well (Only KeePassX uses PasswordPboardType as far as I have seen) and is occasionally requested (#22, #64, and #72).
* Can be enabled/disabled in the preferences and defaults to disabled.
* Makes false positives highly unlikely, since we don't normally copy single words along the line of Password0_Disabled (an example of a reasonable variable name that could produce a false positive), as it requires the copied text contain no spaces, at least one upper case letter, at least one lower case, at least one digit, and at least one symbol and be an exact length that the user has configured.  In the rare case of a developer working on a project that tends toward false positives, the user can easily disable the feature.
* Is automatic when enabled so it is effortless to use and not prone to forgetting.
* Conforms with common good practices for password selection (and to that end encourages good passwords, though I don't think that is an objective of Flycut in any way).
* Doesn't help people with weak passwords, but those people probably aren't using password wallets anyway.

This is a feature I have been using for several years to avoid my passwords being remembered, have found it to be very helpful, and have never experienced false positives or other malfunction in use at home or at work as a coder.  I use a password wallet with a different complex password for everything, so when I need one of those passwords, copy and paste is used a lot.  Not having this feature included means that I have to maintain a separate branch for personal use, diverge from your branch because UI changes don't merge well, and manually transfer changes from my branch to a clone of yours for contribution.  This manual process makes it more time consuming for me to contribute bug fixes, requested features, and enhancements, and makes it less likely that I will choose to do so.  Please consider including this feature with the others.

Thank you,
Mark

**Comment by TermiT** [comment]
Sorry for late reply, I will with it little bit more and come back to you. Thank you for your contribution!

**Comment by MarkJerde** [comment]
Hi Gennadiy,
I added two commits to the branch for this pull request, adding feature request #46 and fixing the preference panel performance, as that was taking five seconds to open.

Thank you!
Mark

**Comment by TermiT** [comment]
Thanks. Btw, do you think we should get rid of Dropbox sync? It doesn't work well, and have issues with sandboxing. Maybe implement iCloud sync instead?

**Comment by MarkJerde** [comment]
Thanks, Gennadiy.
I think iCloud sync is a great idea to replace Dropbox sync.  Without looking deep into it, maybe the Dropbox sync could be fixed by having it put each clipping in a separate new file in a Dropbox directory and keep checking for additions, but I wouldn't bother when iCloud is the more native way to do it.  I'll let you know if I get free time again and start looking into iCloud, so we aren't both doing the same thing.
Mark

**Comment by MarkJerde** [comment]
I added some of my findings relative to iCloud to #23.  I like what I see.  Could be really easy to add this.
Mark

**Pull request merged**
