### PR TITLE
Display source App of clipping and time that it was copied.  Plus bug fixes and dev features.

### PR DESCRIPTION
**Pull request by MarkJerde**
Hi Gennadiy,
This includes all of the changes described in #94.  I have been using it for several days on Mavericks, Yosemite, and El Capitan and am confident in it.

One bug was found in it that would prevent "Position" from being saved to the plist in saveEngine.  That has been fixed, though that value isn't actually used when reading the plist so it wasn't much of an issue.

Thank you!
Mark

### CODE REVIEW

**Comment by hungri-yeti** [comment]
Mark, I just incorporated this into my own fork (just for my own use). This is great work, hopefully it'll be merged into the main project soon!

**Comment by MarkJerde** [comment]
Thanks Ken,
I noticed that your pull request includes the binary nib files.  Since that will make our pull requests mutually exclusive, and mine contains code directed at eliminating this merge problem in the future, would you mind redoing your change on top of mine?
Thank you,
Mark

**Comment by TermiT** [comment]
Thanks!

**Comment by hungri-yeti** [comment]
Hello Mark, I deleted my pull request and redid the changes based on the latest master that incorporates your pull request. Just wanted to confirm that it's ok to check the nib in, you just wanted my changes on top of your changes instead the previous master?

**Comment by MarkJerde** [comment]
Hi Ken,
Yeah. That sounds great. Just make sure you do the changes through XCode, rather than by copying/moving the nib files.
Thanks!

**Pull request merged**
