### PR TITLE
Add preference option to hide the menu item

### PR DESCRIPTION
**Pull request by dounan**
Also adds a preferences icon button to the bezel so you can still access preferences after hiding the menu item.

### CODE REVIEW

**Comment by karlhorky** [comment]
Any luck @dounan? Would be nice to get this merged - it would also close #27.

**Comment by dounan** [comment]
Just merged with latest code. Not sure what else needs to be done to get it merged.

**Comment by MarkJerde** [comment]
It looks like this will clobber any other changes that involve the MainMenu.nib (Preferences, About Window (none, I believe), menu) in the past year.  The Search feature is gone and a lot is missing from the Preferences.  Compare a build of yours against a fresh checkout.  In order to fix this, you'll need to replace your MainMenu.nib with the current one and re-add your checkbox to the Preferences.  This is just the part that really sucks about using the GUI design tools in Xcode.  They create a binary nib file that cannot be merged.  I was just thinking last night, before I saw this, that switching to building the prefs in code would benefit team development of Flycut since it could then be merged.

One other comment, I subscribe to the idea that there should be one commit per feature and one feature per commit.  It looks like you have several commits that make up the "hide" feature.  I often code in a series of commits too, but when I decide I'm done with it I use "git rebase --interactive HEAD~10" (replace 10 with however much history you want) and "squash" the commits together into one.  It also allows you to reorder the commits and delete any you don't want.  I wouldn't squash the indentations in with the others, since it's nice to keep formatting-only changes out of the feature changesets.  The benefits of doing the squash are that it makes it easier to find what it took to add a given feature in case someone needs to do something similar in the future.

The only design nitpick I have is that the wrench icon could be hidden until the user moves the mouse over the bezel.  This is a pretty well established design standard on OS X that helps keep things looking clean yet easy to find.  After all, they aren't going to click it if their mouse isn't over the bezel.

I'll take another look once you have time to get this fixed up.

Thanks!
Mark

**Comment by bronius** [comment]
Mark-
Thanks for taking the time to reply here!   I like the things you're saying
and just want to encourage anyone who has the gumption and know-how to
merge these changes in in the way Mark suggests to take the time to do so.
It'd be a community-wide Christmas present maybe! :)

But I also wanted to add the side note that I also thought it really
peculiar that the GUI tool in XCode did not lend itself to source code
versioning.. So frustrating, so unexpected so I assumed it was just me and
something I was doing..!  Is there a better way?

-Bronius


On Mon, Sep 14, 2015 at 7:57 AM, MarkJerde <notifications@github.com> wrote:

> It looks like this will clobber any other changes that involve the
> MainMenu.nib (Preferences, About Window (none, I believe), menu) in the
> past year. The Search feature is gone and a lot is missing from the
> Preferences. Compare a build of yours against a fresh checkout. In order to
> fix this, you'll need to replace your MainMenu.nib with the current one and
> re-add your checkbox to the Preferences. This is just the part that really
> sucks about using the GUI design tools in Xcode. They create a binary nib
> file that cannot be merged. I was just thinking last night, before I saw
> this, that switching to building the prefs in code would benefit team
> development of Flycut since it could then be merged.
>
> One other comment, I subscribe to the idea that there should be one commit
> per feature and one feature per commit. It looks like you have several
> commits that make up the "hide" feature. I often code in a series of
> commits too, but when I decide I'm done with it I use "git rebase
> --interactive HEAD~10" (replace 10 with however much history you want) and
> "squash" the commits together into one. It also allows you to reorder the
> commits and delete any you don't want. I wouldn't squash the indentations
> in with the others, since it's nice to keep formatting-only changes out of
> the feature changesets. The benefits of doing the squash are that it makes
> it easier to find what it took to add a given feature in case someone needs
> to do something similar in the future.
>
> The only design nitpick I have is that the wrench icon could be hidden
> until the user moves the mouse over the bezel. This is a pretty well
> established design standard on OS X that helps keep things looking clean
> yet easy to find. After all, they aren't going to click it if their mouse
> isn't over the bezel.
>
> I'll take another look once you have time to get this fixed up.
>
> Thanks!
> Mark
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TermiT/Flycut/pull/58#issuecomment-140062640>.
>



-- 
http://www.bronius.com
web | kiosk | drupal development

**Comment by dounan** [comment]
Ah sorry I completely forgot about this, it's been so long. I'll see if I can get some time this next week or two to reimplement this with the latest code.

**Comment by dounan** [comment]
Closing because of lack of time to work on it.

**Pull request closed without merging**
