### PR TITLE
Add preference for a list of apps to ignore, i.e. password managers.

### PR DESCRIPTION
**Pull request by pwxn**
Implements Issue #22
Currently includes LastPass and 1Password but is not enabled by default.

### CODE REVIEW

**Comment by carpeliam** [comment]
:sunglasses: I'd be interested in including [KeePassX](https://www.keepassx.org/) as well.

**Comment by pwxn** [comment]
Well the way it is, users can add whichever app they want in the textbox. I didn't want to hunt down the name of every password manager ever. I added the first two I found, so that the comma separated list was self-documenting; with the intention that a user would replace that with whichever one they use. 

On the other hand, we could easily add that one app to the list by default. 
But where would it end? The relatively small textbox would become unsightly overfull.

**Comment by MarkJerde** [comment]
I agree with pwxn.  There are a multitude of password managers that could be included, and someone probably even has a use case for Preview being ignored, but the feature allows the user to say what they want ignored and pre-supposing their desires beyond what is sufficient to provide an example is unnecessary.

**Comment by unkhz** [comment]
This fixes a good chunk of the problem, but 1Password users at least will still have the problem that the quick copying of password using "1Password mini" is not caught by checking the application name. This is because the focused application is not actually changed when accessing the menubar dropdown or the popup menu with `cmd-alt-\` hotkey. #117 adds a possibility to catch that situation as well.

**Comment by pwxn** [comment]
I went to try to merge updates back into my branch, to fix the conflicts and to make it compatible with sierra. However what I found is that this solution no longer works for lastPass for the same reason unkhz mentioned about "1password mini". LastPass is now hiding itself right after a copy operation, so that by the time FlyCut notices, it is no longer the active application. 

Might still work for other apps, but I ran into merge issues so I never finished the merge. We probably want to close this without merging it, as it seems to not be a valid solution for the two initial use cases, and will probably fail on other apps for similar reasons. 

As a side note, PR #117 is working for me and I'm using that solution.

**Comment by marioc262** [comment]
screen shot 2017-08-07 at 8 43 34 am
Hi, I added a preference tab to select which app to ignore, the code is complete, and can be provided if wanted. (Had not seen this pull-request until I was done) 
It allow wild card matching on Bundle Identifier which solves the issue of 1Password mini.

**Comment by pwxn** [comment]
Canceling this pull request as it has been filled by other features.

**Pull request closed without merging**
